### PR TITLE
add download test file

### PR DESCRIPTION
**Pull request by edward-edberg**
Screen Shot 2020-07-18 at 5 19 50 AM

### CODE REVIEW

**Comment by edward-edberg** [comment]
add train file, auto input labels
Screen Shot 2020-07-18 at 5 38 41 AM

**Comment by edward-edberg** [comment]
not done yet

**Comment by davidatbu** [comment]
Looks good!

1. Can we change "Try our Train File" to "Try our <dataset_name> dataset"? Similarly, can we change "try our test file", "try an unlablled set for <dataset_name>"?

And, instead of having a different link for "input our labels", why don't we automatically fill in the labels when they download click on "try our <dataset_name> dataset?"

**Comment by edward-edberg** [comment]
When client clicks "Try Our Test File", it will download csv file. Client have to upload it again by clicking "choose file"
The reason behind this is to let the client know about what's inside the csv file.

Should I change it to autofill the "choose file"?

**Comment by edward-edberg** [comment]
wait I just realized we cannot do that (autofill choose file)

**Comment by edward-edberg** [comment]
So, we need have a new menu bar to show some topics that we have to address <dataset_name>? Currently, we only have gun violence dataset.

Could you explain it a bit more?

**Comment by monajalal** [comment]
Screen Shot 2020-07-17 at 9 35 11 PM

I don't think this part is super intuitive.

**Comment by edward-edberg** [comment]
Latest Update: When client click "Try Our Train File" button, it will auto-fill others, categories, download csv file
Screen Shot 2020-07-18 at 8 38 22 AM

**Comment by monajalal** [comment]
Sounds great!

**Comment by monajalal** [comment]
It's still the same for 'other' category.

Screen Shot 2020-07-17 at 9 42 29 PM

We shouldn't make it super confusing for the user to click on two buttons. What about auto-filling the frame names for 'our train file'? This way, the user doesn't have to click on yet another button.

**Comment by edward-edberg** [comment]
I haven't committed it yet.. I ask for your opinion first hahaha

**Comment by edward-edberg** [comment]
Now, I'll split framing.html into 2 parts. Perhaps will add drop downs on navigation bar.

**Pull request merged**
