### PR TITLE
Add openframing logo

### PR DESCRIPTION
**Pull request by edward-edberg**
Screen Shot 2020-07-15 at 2 08 02 AM

### CODE REVIEW

**Comment by monajalal** [comment]
so @edward-edberg  in FireFox, the OpenFraming logo is not showing and instead WebStorm (WS) logo is showing. Which browsers have you tested the code with?

Screen Shot 2020-07-14 at 4 21 51 PM

**Comment by edward-edberg** [comment]
only google chrome

**Comment by monajalal** [comment]
@edward-edberg could you please try it usually for the following well-known browsers:

1. Firefox
2. Safari
3. Chrome

Including this issue?

That would be more reliable and great.

**Comment by edward-edberg** [comment]
I couldn't see any logo in Safari. I guess all websites didn't show any logo there.

It works in Mozilla, Chrome. Maybe you need to update the firefox?
Screen Shot 2020-07-15 at 3 58 46 AM

**Pull request merged**
