### PR TITLE
edit text to help the reviewers to understand our web better.

### PR DESCRIPTION
**Pull request by edward-edberg**
Hi guys, I want to edit the text to help the reviewers to understand our web better. What do you think?

Screen Shot 2020-09-20 at 7 20 03 AM

### CODE REVIEW

**Comment by edward-edberg** [comment]
before
Screen Shot 2020-09-20 at 7 55 53 AM

after
Screen Shot 2020-09-20 at 7 56 15 AM

basically, I added some bold texts to make the selection process (use pretrained model or create a new one) more obvious because it could be confusing for the first time when someone new come to our web.

**Comment by edward-edberg** [comment]
@davidatbu could you rerun the web? I just make some changes so the reviewer could understand our web better.

**Comment by davidatbu** [comment]
Hi Edward,

Sorry for long wait. I will do so later today.

**Comment by davidatbu** [comment]
Hi Edward,

I've pushed the changes to the deployed server.

**Pull request merged**
